### ISSUE TITLE
Document refactoring plan for Clipper::clip

### ISSUE THREAD

**Issue by bjornthiberg** [group19-se24/assignment-3#16]

**Comment by Samkth123** [comment]
1. Splitting based on geometry type
The clipping operation can be made into different methods based on the geometry type, and the main clip function can be made to route instead of implementing all the logic for these aswell.

The refactoring would be to make each geometry type (Point, Envelope, MultiPoint, Polygon, Polyline) into different methods, and each method would handle the clipping logic specific to that geometry type.


2. Simplify the conditional blocks

Many of the conditional blocks can be made into separate methods which would make the main logic more straightforward.

The refactoring would be to take blocks that check the geometry attributes ex if geometry is empty or extent is empty, and then instead create methods for them ex. isGeometryEmpty(Geometry geometry) and isExtentEmpty(Envelope2D extent).

For operations that are repeated across different geometry types, like checking intersection with the extent, we can create methods that can be reused.
